import type { Connection } from "./types";

export const connections: Connection[] = [
  { source: "garry-nolan", target: "jacques-vallee", type: "co-authored", note: "2022 Progress in Aerospace Sciences materials analysis", year: "2022" },
  { source: "roger-penrose", target: "stuart-hameroff", type: "co-authored", note: "Orch-OR framework papers", year: "1990s" },
  { source: "colm-kelleher", target: "george-knapp", type: "co-authored", note: "Hunt for the Skinwalker", year: "2005" },
  { source: "luis-elizondo", target: "chris-mellon", type: "co-founded", note: "To The Stars Academy", year: "2017" },
  { source: "luis-elizondo", target: "hal-puthoff", type: "co-founded", note: "To The Stars Academy", year: "2017" },
  { source: "luis-elizondo", target: "jim-semivan", type: "co-founded", note: "To The Stars Academy", year: "2017" },
  { source: "garry-nolan", target: "chris-mellon", type: "co-founded", note: "Sol Foundation", year: "2023" },
  { source: "garry-nolan", target: "tim-gallaudet", type: "co-founded", note: "Sol Foundation", year: "2023" },
  { source: "garry-nolan", target: "jacques-vallee", type: "co-founded", note: "Sol Foundation", year: "2023" },
  { source: "chris-mellon", target: "tim-gallaudet", type: "co-founded", note: "Sol Foundation", year: "2023" },
  { source: "chris-mellon", target: "jacques-vallee", type: "co-founded", note: "Sol Foundation", year: "2023" },
  { source: "tim-gallaudet", target: "jacques-vallee", type: "co-founded", note: "Sol Foundation", year: "2023" },
  { source: "karl-nell", target: "chris-mellon", type: "co-founded", note: "Sol Foundation", year: "2023" },
  { source: "david-grusch", target: "ryan-graves", type: "co-testified", note: "House National Security subcommittee UAP hearing", year: "2023" },
  { source: "luis-elizondo", target: "michael-shellenberger", type: "co-testified", note: "Jan 23, 2026 House Oversight hearing", year: "2026" },
  { source: "luis-elizondo", target: "chris-mellon", type: "co-testified", note: "Jan 23, 2026 House Oversight hearing", year: "2026" },
  { source: "luis-elizondo", target: "tim-gallaudet", type: "co-testified", note: "Jan 23, 2026 House Oversight hearing", year: "2026" },
  { source: "michael-shellenberger", target: "chris-mellon", type: "co-testified", note: "Jan 23, 2026 House Oversight hearing", year: "2026" },
  { source: "dylan-borland", target: "jeffrey-nuccetelli", type: "co-testified", note: "Sept 9, 2025 whistleblower protection hearing", year: "2025" },
  { source: "dylan-borland", target: "george-knapp", type: "co-testified", note: "Sept 9, 2025 whistleblower protection hearing", year: "2025" },
  { source: "jeffrey-nuccetelli", target: "george-knapp", type: "co-testified", note: "Sept 9, 2025 whistleblower protection hearing", year: "2025" },
  { source: "alexandro-wiggins", target: "george-knapp", type: "co-testified", note: "Sept 9, 2025 whistleblower protection hearing", year: "2025" },
  { source: "colm-kelleher", target: "george-knapp", type: "investigated-together", note: "Skinwalker Ranch / BAASS investigation", year: "2008" },
  { source: "colm-kelleher", target: "jay-stratton", type: "investigated-together", note: "Skinwalker Ranch / UAPTF overlap", year: "2020" },
  { source: "colm-kelleher", target: "travis-taylor", type: "investigated-together", note: "Skinwalker Ranch investigations", year: "2020" },
  { source: "robert-bigelow", target: "colm-kelleher", type: "investigated-together", note: "BAASS / Skinwalker Ranch", year: "2008" },
  { source: "garry-nolan", target: "jacques-vallee", type: "investigated-together", note: "UAP materials analysis program", year: "2022" },
  { source: "anna-paulina-luna", target: "sean-kirkpatrick", type: "public-dispute", note: "Called Kirkpatrick 'documented liar' on Congressional record", year: "2024" },
  { source: "chris-mellon", target: "sean-kirkpatrick", type: "public-dispute", note: "AARO historical report 'most error-ridden'", year: "2024" },
  { source: "avi-loeb", target: "sean-kirkpatrick", type: "public-dispute", note: "Critique of AARO posture on interstellar objects", year: "2025" },
  { source: "hal-puthoff", target: "ingo-swann", type: "mentor-mentee", note: "SRI coordinate remote viewing protocol", year: "1970s" },
  { source: "ingo-swann", target: "joe-mcmoneagle", type: "mentor-mentee", note: "Stargate operational lineage", year: "1980s" },
  { source: "robert-bigelow", target: "colm-kelleher", type: "funded", note: "BAASS / DIA AAWSAP $22M Skinwalker program", year: "2008" },
  { source: "mike-turner", target: "mike-rogers", type: "public-dispute", note: "Both cited as UAPDA legislative blockers in insider accounts", year: "2025" },
  { source: "hunt-willis", target: "chris-mellon", type: "investigated-together", note: "Disclosure Foundation FOIA litigation on NSA UMBRA records", year: "2026" },
  { source: "tim-gallaudet", target: "hunt-willis", type: "investigated-together", note: "Disclosure Foundation advisory / testimony ecosystem", year: "2026" },
  { source: "hal-puthoff", target: "chris-mellon", type: "co-founded", note: "Disclosure Foundation Advisory Board, Dec 2025", year: "2025" },
  { source: "kyle-fish", target: "garry-nolan", type: "investigated-together", note: "AI consciousness / welfare research parallel to NHI materials science", year: "2026" },
  { source: "kyle-fish", target: "dario-amodei", type: "investigated-together", note: "Anthropic — AI welfare research", year: "2026" },
  { source: "kyle-fish", target: "david-chalmers", type: "co-authored", note: "Taking AI Welfare Seriously", year: "2026" },
  { source: "jack-lindsey", target: "dario-amodei", type: "investigated-together", note: "Anthropic — model psychiatry / interpretability", year: "2026" },
  { source: "tim-gallaudet", target: "ryan-graves", type: "co-founded", note: "Americans for Safe Aerospace advisory ecosystem", year: "2026" },
  { source: "tim-gallaudet", target: "peter-skafish", type: "co-founded", note: "Sol Foundation — PURSUE Release 01 statement", year: "2026" },
  { source: "kirk-mcconnell", target: "chris-mellon", type: "investigated-together", note: "Disclosure Foundation advisory", year: "2026" },
  { source: "peter-skafish", target: "garry-nolan", type: "co-founded", note: "Sol Foundation leadership", year: "2023" },
  { source: "julia-mossbridge", target: "garry-nolan", type: "public-dispute", note: "Buga Sphere skeptical vs endorsing camps", year: "2026" },
  { source: "julia-mossbridge", target: "steven-greer", type: "public-dispute", note: "Buga Sphere material analysis", year: "2026" },
  { source: "eric-burlison", target: "steven-greer", type: "co-testified", note: "Buga Sphere press conference, June 2025", year: "2025" },
  { source: "federico-faggin", target: "giacomo-dariano", type: "co-authored", note: "Quantum Information Panpsychism (2025)", year: "2025" },
  { source: "michael-wiest", target: "stuart-hameroff", type: "investigated-together", note: "Orch-OR experimental support line", year: "2025" },
  { source: "kevin-cann", target: "avi-loeb", type: "investigated-together", note: "VASCO / 3I/ATLAS anomaly literature", year: "2026" },
];
