import type { Figure } from "./types";

export const originalFigures: Figure[] = [
  {
    id: "john-alexander",
    name: "John Alexander",
    category: "government-military",
    affiliations: ["Department of War (formerly DoD)"],
    role: "Retired Army colonel; Pentagon non-lethal weapons program; UAP investigator-author",
    bio: "Retired U.S. Army Colonel; former head of the Pentagon's non-lethal weapons program. Author of UFOs: Myths, Conspiracies, and Realities (2011). A rare insider who investigated UAP phenomena through official channels and concluded they are real but resisted simple explanation.",
    stakeholderFlags: [],
    status: "retired",
  },
  {
    id: "robert-bigelow",
    name: "Robert Bigelow",
    category: "witness-experiencer",
    affiliations: ["AAWSAP / BAASS", "Skinwalker Ranch"],
    role: "BAASS founder; Skinwalker Ranch owner; DIA AAWSAP contractor",
    bio: "Aerospace entrepreneur and founder of Bigelow Aerospace Advanced Space Studies (BAASS). Funded AAWSAP under a $22M DIA contract (2008). Owner of Skinwalker Ranch (1996–2016); hosted one of the most intensive multi-year scientific investigations of UAP and anomalous phenomena ever conducted.",
    stakeholderFlags: ["defense-contractor", "disclosure-advocate"],
    status: "active",
  },
  {
    id: "chris-bledsoe",
    name: "Chris Bledsoe",
    category: "witness-experiencer",
    affiliations: [],
    role: "North Carolina contactee; 'The Lady' NHI interactions investigated by scientists and IC",
    bio: "North Carolina contactee whose decade-plus interactions with a luminous feminine NHI entity called 'The Lady' have been investigated by NASA scientists, CIA officers, and MUFON researchers. His contact experiences include apparent telepathic communication, healing events, and a prophecy referencing the 2026 Regulus/Sphinx astronomical alignment.",
    stakeholderFlags: ["experiencer"],
    status: "active",
  },
  {
    id: "eric-davis",
    name: "Eric Davis",
    category: "intelligence-community",
    affiliations: ["AAWSAP / BAASS"],
    role: "Physicist; Wilson-Davis memo co-author; Earthtech senior scientist",
    bio: "Physicist; senior research scientist at Earthtech International. Co-author of the alleged Wilson-Davis memo (2002), allegedly recording a conversation in which Vice Admiral Wilson was denied access to a contractor-held UAP program. Has neither confirmed nor denied the memo's authenticity, citing classification obligations.",
    stakeholderFlags: ["intel-community", "contested-status"],
    status: "active",
    calibrationNote:
      "The Wilson-Davis memo has been entered into the Congressional Record but has not been officially confirmed or denied by Davis or Wilson. Its contents remain contested evidence, not established fact.",
  },
  {
    id: "luis-elizondo",
    name: "Luis Elizondo",
    category: "intelligence-community",
    affiliations: [
      "To The Stars Academy (TTSA)",
      "UAPTF (Unidentified Aerial Phenomena Task Force, 2020–2022)",
      "The Age of Disclosure (2025)",
      "January 23, 2026 Congressional Hearing",
    ],
    role: "Former AATIP director; TTSA co-founder; Five Observables primary source",
    bio: "Former DIA counterintelligence officer; director of AATIP (2010–2017). Resigned citing ethical objections. Author of Imminent (2024), #1 New York Times bestseller. Co-founded TTSA. Primary source establishing the 'Five Observables' as technical descriptors for UAP. Has confirmed UAP-nuclear nexus publicly.",
    stakeholderFlags: ["disclosure-advocate"],
    status: "active",
  },
  {
    id: "tim-gallaudet",
    name: "Tim Gallaudet",
    category: "government-military",
    affiliations: [
      "Sol Foundation",
      "The Age of Disclosure (2025)",
      "January 23, 2026 Congressional Hearing",
    ],
    role: "Rear Admiral (Ret.); former Acting NOAA Administrator; Sol Foundation member",
    bio: "Rear Admiral (Ret.), U.S. Navy; former Acting NOAA Administrator; oceanographer. Member of the Sol Foundation. Has stated publicly that UAP phenomena are real and have been documented extensively by military platforms. Participated in Japan's 2025 Diet session UAP briefing.",
    stakeholderFlags: ["disclosure-advocate"],
    status: "retired",
  },
  {
    id: "david-grusch",
    name: "David Grusch",
    category: "intelligence-community",
    affiliations: [
      "UAPTF (Unidentified Aerial Phenomena Task Force, 2020–2022)",
      "House UAP Caucus",
    ],
    role: "Former NRO analyst; July 2023 whistleblower testimony; Congressional adviser to Burlison",
    bio: "Former National Reconnaissance Office senior analyst and UAP Task Force representative. Testified under oath before the House Oversight Committee (July 2023) alleging a multi-decade non-human intelligence recovery and reverse-engineering program. Hired as Congressional adviser to Rep. Eric Burlison (March 2025).",
    stakeholderFlags: ["disclosure-advocate", "whistleblower"],
    status: "active",
  },
  {
    id: "stuart-hameroff",
    name: "Stuart Hameroff",
    category: "scientist-academic",
    affiliations: [],
    role: "University of Arizona anesthesiologist; Orch-OR co-developer with Penrose",
    bio: "Anesthesiologist and consciousness researcher at the University of Arizona. Co-developer with Roger Penrose of Orchestrated Objective Reduction (Orch-OR), which proposes consciousness arises from quantum computations in neural microtubules. Has actively integrated experimental evidence from microtubule anesthetic studies since 2015.",
    stakeholderFlags: [],
    status: "active",
  },
  {
    id: "donald-hoffman",
    name: "Donald Hoffman",
    category: "scientist-academic",
    affiliations: [],
    role: "UC Irvine cognitive scientist; Interface Theory of Perception; Conscious Realism",
    bio: "Cognitive scientist at UC Irvine. Developed the Interface Theory of Perception and Conscious Realism through extensive evolutionary game theory modeling. Author of The Case Against Reality (W.W. Norton, 2019). His work implies UAP 'violations of physical law' may represent operations at a level more fundamental than the perceptual interface.",
    stakeholderFlags: [],
    status: "active",
  },
  {
    id: "colm-kelleher",
    name: "Colm Kelleher",
    category: "scientist-academic",
    affiliations: ["AAWSAP / BAASS", "Skinwalker Ranch"],
    role: "BAASS/NIDSci lead scientist; Skinwalker hitchhiker effect documenter",
    bio: "Molecular biologist; lead scientist at BAASS/NIDSci during the Skinwalker Ranch investigation (1996–2004, 2008–2010). Co-author of Hunt for the Skinwalker (2005) with George Knapp. Documented the hitchhiker effect — post-encounter anomalous phenomena following witnesses off-site — in systematic detail.",
    stakeholderFlags: [],
    status: "active",
  },
  {
    id: "sean-kirkpatrick",
    name: "Sean Kirkpatrick",
    category: "intelligence-community",
    affiliations: ["AARO (All-domain Anomaly Resolution Office)"],
    role: "Former AARO Director (2022–2023); published no-credible-evidence conclusion",
    bio: "Former AARO Director (2022–2023). Published op-ed concluding 'no credible evidence' of extraterrestrial craft while admitting he lobbied against the UAP Records Review Board. Called 'a documented liar' on the Congressional record by Representative Anna Paulina Luna.",
    stakeholderFlags: ["contested-status"],
    status: "retired",
    calibrationNote:
      "Representative Luna's 'documented liar' characterization is on the Congressional record. Kirkpatrick maintains his AARO findings are accurate and has publicly critiqued PURSUE Release 01 as light on substantive content. Both positions are on the public record.",
  },
  {
    id: "jon-kosloski",
    name: "Jon Kosloski",
    category: "government-military",
    affiliations: ["AARO (All-domain Anomaly Resolution Office)"],
    role: "AARO Director; NSA quantum-optics researcher acknowledging unexplained cases",
    bio: "Successor to Sean Kirkpatrick as AARO Director; NSA researcher with quantum optics background. Acknowledged 21 UAP cases his physics and engineering background cannot explain — a markedly different posture than his predecessor's categorical denial.",
    stakeholderFlags: [],
    status: "active",
  },
  {
    id: "avi-loeb",
    name: "Avi Loeb",
    category: "scientist-academic",
    affiliations: ["Galileo Project"],
    role: "Harvard astrophysicist; Galileo Project founder; interstellar object researcher",
    bio: "Harvard astrophysicist; former chair of Harvard's astronomy department. Founder of the Galileo Project, which deploys AI-assisted sensor arrays to systematically search for extraterrestrial artifacts. Led the Pacific Ocean expedition that recovered spherules from the first confirmed interstellar object, CNEOS 2014-01-08.",
    stakeholderFlags: ["disclosure-advocate"],
    status: "active",
  },
  {
    id: "anna-paulina-luna",
    name: "Anna Paulina Luna",
    category: "legislator",
    affiliations: ["House UAP Caucus"],
    role: "House UAP Caucus co-chair; AARO accountability and whistleblower protection advocate",
    bio: "U.S. Representative (R-FL); co-chair of the House UAP Caucus. Called AARO's Sean Kirkpatrick 'a documented liar' on the Congressional record. Introduced legislation requiring UAP whistleblower protection and ordered AARO be disbanded as of 2026. A leading legislative voice for disclosure accountability.",
    stakeholderFlags: ["disclosure-advocate"],
    status: "active",
  },
  {
    id: "nancy-mace",
    name: "Nancy Mace",
    category: "legislator",
    affiliations: ["House UAP Caucus", "January 23, 2026 Congressional Hearing"],
    role: "House Oversight UAP hearings; whistleblower intimidation inquiries",
    bio: "U.S. Representative (R-SC). Conducted public inquiries characterizing AARO's secrecy as excessive and documenting credible reports of whistleblower intimidation. Hosted a July 2023 House Oversight Committee hearing on UAP whistleblowers that included David Grusch's landmark testimony.",
    stakeholderFlags: ["disclosure-advocate"],
    status: "active",
  },
  {
    id: "joe-mcmoneagle",
    name: "Joe McMoneagle",
    category: "witness-experiencer",
    affiliations: ["Project Stargate (SRI)"],
    role: "Army remote viewer (Ret.); documented Project Stargate operative",
    bio: "U.S. Army remote viewer (Warrant Officer, Ret.); one of the most documented Project Stargate operatives. Author of Mind Trek (1993). His operational remote viewing record, partially declassified, includes claimed contributions to intelligence collection confirmed by Stargate program directors.",
    stakeholderFlags: ["intel-community"],
    status: "retired",
  },
  {
    id: "chris-mellon",
    name: "Chris Mellon",
    category: "intelligence-community",
    affiliations: [
      "To The Stars Academy (TTSA)",
      "Sol Foundation",
      "The Age of Disclosure (2025)",
      "January 23, 2026 Congressional Hearing",
    ],
    role: "Former DASD for Intelligence; Nimitz video leaker; Sol Foundation co-founder",
    bio: "Former Deputy Assistant Secretary of Defense for Intelligence; former Senate Intelligence Committee staff director. Co-founded TTSA with Elizondo. Leaked the Nimitz encounter videos to the New York Times (2017). Called the AARO Historical Report 'the most error-ridden and unsatisfactory' he had encountered. Sol Foundation member.",
    stakeholderFlags: ["disclosure-advocate"],
    status: "active",
  },
  {
    id: "karl-nell",
    name: "Karl Nell",
    category: "government-military",
    affiliations: [
      "Sol Foundation",
      "UAPTF (Unidentified Aerial Phenomena Task Force, 2020–2022)",
    ],
    role: "Retired Army colonel; UAPTF attaché; zero-doubt NHI statements at SALT 2024",
    bio: "Retired U.S. Army Colonel; former Army attaché to the UAP Task Force. Aerospace executive. Stated at the 2024 SALT conference that he has 'zero doubt' non-human intelligence exists and interacts with humanity. Presented a five-phase disclosure roadmap at Stanford's Sol Foundation Symposium (2023); targets full transparency by October 2030.",
    stakeholderFlags: ["disclosure-advocate"],
    status: "retired",
  },
  {
    id: "garry-nolan",
    name: "Garry Nolan",
    category: "scientist-academic",
    affiliations: ["Sol Foundation", "Sol Foundation 2025 Italy Symposium"],
    role: "Stanford immunologist; UAP experiencer brain imaging; materials analysis with Vallée",
    bio: "Stanford University immunologist; inventor of Hyperion mass cytometry platform (licensed to Fluidigm). Conducted MRI studies of over 100 military and intelligence personnel documenting extreme caudate-putamen hypermorphism in UAP experiencers. Co-published materials analysis of alleged UAP samples with Jacques Vallée in Progress in Aerospace Sciences (2022). Co-founder of the Sol Foundation.",
    stakeholderFlags: ["disclosure-advocate"],
    status: "active",
  },
  {
    id: "diana-walsh-pasulka",
    name: "Diana Walsh Pasulka",
    category: "scientist-academic",
    affiliations: [],
    role: "UNC Wilmington religious studies professor; American Cosmic author",
    bio: "Professor of religious studies at UNC Wilmington; author of American Cosmic (Oxford UP, 2019) and Encounters (2023). Studies the sociological and religious dimensions of UAP belief, documenting scientists, military professionals, and engineers who privately hold UAP experiences as central to their lives and work.",
    stakeholderFlags: ["experiencer"],
    status: "active",
  },
  {
    id: "hal-puthoff",
    name: "Hal Puthoff",
    category: "intelligence-community",
    affiliations: ["To The Stars Academy (TTSA)", "Project Stargate (SRI)"],
    role: "Physicist; SRI remote viewing co-director; TTSA director",
    bio: "Physicist; co-director (with Russell Targ) of SRI International's remote viewing research program under CIA/DIA contract. Later joined Elizondo's TTSA as a director. Has stated publicly that he has seen classified evidence of recovered non-human materials. Founded the Institute for Advanced Studies at Austin.",
    stakeholderFlags: ["disclosure-advocate", "intel-community"],
    status: "active",
  },
  {
    id: "mike-rogers",
    name: "Mike Rogers",
    category: "legislator",
    affiliations: ["House UAP Caucus"],
    role: "Former HPSCI Chair; Lockheed PAC recipient; cited UAPDA dilution critic",
    bio: "Former U.S. Representative (R-MI); former Chair of the House Permanent Select Committee on Intelligence. Federal Election Commission records document $143,000 in contributions from Lockheed Martin PAC and associated personnel. Critics have linked his committee's oversight role to repeated UAPDA dilution.",
    stakeholderFlags: ["legislative-blocker", "defense-contractor"],
    status: "retired",
  },
  {
    id: "jim-semivan",
    name: "Jim Semivan",
    category: "intelligence-community",
    affiliations: ["To The Stars Academy (TTSA)"],
    role: "Retired CIA SIS officer (25 years); TTSA co-founder; Bledsoe case investigator",
    bio: "Retired CIA Senior Intelligence Service officer (25 years). Co-founder of TTSA. Investigated the Chris Bledsoe contact case. Has stated publicly that non-human intelligence is real and interacts with humanity. One of the most credentialed intelligence community figures to make unequivocal public statements about NHI reality.",
    stakeholderFlags: ["disclosure-advocate"],
    status: "retired",
  },
  {
    id: "maria-stromme",
    name: "Maria Strømme",
    category: "scientist-academic",
    affiliations: [],
    role: "Uppsala nanotechnology professor; field theory of consciousness (AIP Advances 2025)",
    bio: "Professor of nanotechnology at Uppsala University; one of Europe's most-cited applied physics researchers. Published 'A Field Theory of Consciousness' in AIP Advances (November 2025), selected as best paper of the issue. Proposes consciousness as a fundamental physical field prior to and generative of spacetime — with testable predictions.",
    stakeholderFlags: [],
    status: "active",
  },
  {
    id: "ingo-swann",
    name: "Ingo Swann",
    category: "witness-experiencer",
    affiliations: ["Project Stargate (SRI)"],
    role: "SRI coordinate remote viewing protocol co-developer; Penetration author",
    bio: "New York artist and pioneering remote viewer; co-developer (with Hal Puthoff and Russell Targ) of the 'coordinate remote viewing' protocol at SRI International. Author of Penetration (1998), describing claimed classified remote viewing sessions of non-human activity on the Moon. His operational records remain partially classified.",
    stakeholderFlags: ["intel-community"],
    status: "deceased",
  },
  {
    id: "matthew-szydagis",
    name: "Matthew Szydagis",
    category: "scientist-academic",
    affiliations: [],
    role: "SUNY Albany physicist; UAP disclosure statistical modeling in Limina",
    bio: "Physicist at the University at Albany (SUNY); developer of the NEST radiation detection simulation. Applied statistical modeling to UAP disclosure scenarios in a series of papers in Limina: The Journal of UAP Studies, estimating mean catastrophic disclosure year at 2040 based on surveillance technology proliferation.",
    stakeholderFlags: [],
    status: "active",
  },
  {
    id: "mike-turner",
    name: "Mike Turner",
    category: "legislator",
    affiliations: ["House UAP Caucus"],
    role: "HPSCI Chair; Wright-Patterson district; Lockheed PAC recipient",
    bio: "U.S. Representative (R-OH); former Chair of the House Permanent Select Committee on Intelligence. His district geographically encircles Wright-Patterson Air Force Base. FEC records document $186,250 from Lockheed Martin PAC; critics have argued his committee's oversight role correlates with UAPDA dilution.",
    stakeholderFlags: ["legislative-blocker", "defense-contractor"],
    status: "active",
  },
  {
    id: "jacques-vallee",
    name: "Jacques Vallée",
    category: "scientist-academic",
    affiliations: ["Sol Foundation", "Sol Foundation 2025 Italy Symposium"],
    role: "Astrophysicist-venture capitalist; Passport to Magonia; Nolan materials co-author",
    bio: "French-American astrophysicist, computer scientist, and venture capitalist. A pioneer of both artificial intelligence (astrophysics computing at Northwestern, 1960s) and UAP research. Author of Passport to Magonia (1969), which proposed the interdimensional/control system hypothesis. Co-published materials analysis with Garry Nolan (2022). Sol Foundation member.",
    stakeholderFlags: ["disclosure-advocate"],
    status: "active",
  },
  {
    id: "thomas-wilson",
    name: "Thomas Wilson",
    category: "government-military",
    affiliations: [],
    role: "Former DIA Director; Wilson-Davis memo central figure",
    bio: "Vice Admiral (Ret.); former Director of the Defense Intelligence Agency (1999–2002). Central figure in the Wilson-Davis memo, which alleges he was denied access to a contractor-held UAP program despite his position. Wilson has publicly denied the meeting occurred. The memo was entered into the Congressional Record as SD001 in November 2024.",
    stakeholderFlags: [],
    status: "retired",
  },
  {
    id: "roger-penrose",
    name: "Roger Penrose",
    category: "scientist-academic",
    affiliations: [],
    role: "Nobel laureate mathematical physicist; Orch-OR co-developer with Hameroff",
    bio: "Mathematical physicist; Nobel Prize laureate (2020); emeritus professor at Oxford. Co-developer (with Stuart Hameroff) of Orchestrated Objective Reduction (Orch-OR). Author of The Emperor's New Mind (1989) and Shadows of the Mind (1994), arguing consciousness involves non-computable quantum processes beyond algorithmic replication.",
    stakeholderFlags: [],
    status: "active",
  },
];
