import type { Config } from "tailwindcss";
import typography from "@tailwindcss/typography";

export default {
  darkMode: ["class"],
  content: [
    "./app/**/*.{ts,tsx,md,mdx}",
    "./pages/**/*.{ts,tsx,md,mdx}",
    "./components/**/*.{ts,tsx,md,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "#0f1115",
        panel: "#161a22",
        border: "#2a2f3a",
        text: "#e6e8ec",
        muted: "#a6adbb",
        accent: "#9bbcff",
        warning: "#e6b566",
        danger: "#d17a7a",
        success: "#7fb69c",
      },
      fontFamily: {
        sans: ["var(--font-body)", "Inter", "system-ui", "sans-serif"],
        serif: ["var(--font-heading)", "Cormorant Garamond", "Georgia", "serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "body-sm": ["1rem", { lineHeight: "1.75" }],
        body: ["1.125rem", { lineHeight: "1.85" }],
        "body-lg": ["1.25rem", { lineHeight: "1.85" }],
      },
      maxWidth: { prose: "72ch" },
      boxShadow: {
        panel: "0 10px 30px rgba(0,0,0,0.45)",
      },
      borderRadius: { xl: "14px" },
      typography: (theme: (s: string) => string) => ({
        DEFAULT: {
          css: {
            color: theme("colors.text"),
            maxWidth: theme("maxWidth.prose"),
            fontSize: "1.125rem",
            lineHeight: "1.85",
            a: {
              color: theme("colors.accent"),
              textDecoration: "none",
              borderBottom: `1px solid ${theme("colors.accent")}33`,
            },
            "a:hover": { borderBottomColor: theme("colors.accent") },
            p: {
              marginTop: "1.25em",
              marginBottom: "1.25em",
            },
            h1: {
              fontFamily: "var(--font-heading)",
              color: theme("colors.text"),
              fontSize: "3.25rem",
              fontWeight: "600",
              letterSpacing: "-0.03em",
              lineHeight: "1.1",
            },
            h2: {
              fontFamily: "var(--font-heading)",
              color: theme("colors.text"),
              fontSize: "2.25rem",
              fontWeight: "500",
              letterSpacing: "-0.025em",
              lineHeight: "1.2",
              borderBottom: `1px solid rgba(155,188,255,0.10)`,
              paddingBottom: "0.35rem",
            },
            h3: {
              fontFamily: "var(--font-heading)",
              color: theme("colors.text"),
              fontSize: "1.65rem",
              fontWeight: "500",
              letterSpacing: "-0.02em",
            },
            h4: { color: theme("colors.muted") },
            strong: { color: theme("colors.text") },
            li: { marginTop: "0.5em", marginBottom: "0.5em" },
            "ul > li": { paddingLeft: "1.5em" },
            blockquote: {
              fontFamily: "var(--font-heading)",
              fontSize: "1.25rem",
              fontStyle: "italic",
              lineHeight: "1.65",
              color: theme("colors.muted"),
              borderLeftColor: theme("colors.accent"),
              backgroundColor: "rgba(155,188,255,0.04)",
              padding: "1rem 1.5rem",
              borderRadius: "0.75rem",
            },
            code: {
              fontFamily: "var(--font-mono)",
              color: theme("colors.text"),
              fontSize: "0.9em",
              backgroundColor: theme("colors.panel"),
              padding: "0.15em 0.35em",
              borderRadius: "0.35rem",
              fontWeight: "500",
            },
            "code::before": { content: '""' },
            "code::after": { content: '""' },
            pre: {
              backgroundColor: theme("colors.panel"),
              border: `1px solid ${theme("colors.border")}`,
              borderRadius: "0.75rem",
            },
            hr: { borderColor: theme("colors.border") },
            th: { color: theme("colors.muted") },
            td: { borderBottomColor: theme("colors.border") },
          },
        },
      }),
    },
  },
  plugins: [typography],
} satisfies Config;
